from typing import List


def generate_playwright_imports() -> List[str]:
    return [
        "import re",
        "import asyncio",
        "import os",
        "import sys",
        "import time",
        "from datetime import datetime, timezone",
        "import json",
        "import hashlib",
        "import traceback",
        "",
        "from playwright.async_api import async_playwright, expect",
        "",
    ]


def generate_playwright_guard() -> List[str]:
    return [
        "def _get_step_source(step_fn):",
        "    \"\"\"",
        "    Extracts the source code of the given step function directly from the file.",
        "    Does not use the 'inspect' module to remain compliant with strict sandboxes.",
        "    \"\"\"",
        "    try:",
        "        with open(__file__, 'r', encoding='utf-8') as f:",
        "            content = f.read()",
        "        ",
        "        func_name = step_fn.__name__",
        "        # Match function definition with flexible spacing",
        "        pattern = rf\"async\\s+def\\s+{func_name}\\s*\\(\\s*page\\s*\\)\\s*:\"",
        "        match = re.search(pattern, content)",
        "        if not match:",
        "            return \"\"",
        "        ",
        "        start_pos = match.end()",
        "        lines = content[start_pos:].splitlines()",
        "        body_lines = []",
        "        body_indent = None",
        "        ",
        "        for line in lines:",
        "            if not line.strip():",
        "                if body_indent is not None:",
        "                    body_lines.append(line)",
        "                continue",
        "            ",
        "            indent = len(line) - len(line.lstrip())",
        "            if body_indent is None:",
        "                body_indent = indent",
        "            ",
        "            if indent < body_indent:",
        "                break",
        "                ",
        "            # Strip body indentation to match original representation",
        "            body_lines.append(line[body_indent:] if len(line) >= body_indent else line)",
        "            ",
        "        return \"\\n\".join(body_lines).strip()",
        "    except Exception:",
        "        return \"\"",
        "",
        "async def _guarded_step(page, step_fn, step_name, step_index, step_code, step_intent, max_retries, artifacts_dir, success_dir, step_metrics, summary_path):",
        "    attempts = 0",
        "    start_total = time.monotonic()",
        "    last_dom_hash = None",
        "",
        "    for attempt in range(max_retries + 1):",
        "        attempts += 1",
        "        console_logs = []",
        "        def on_console(msg):",
        "            try:",
        "                console_logs.append(msg.text)",
        "            except Exception:",
        "                console_logs.append(str(msg))",
        "",
        "        page.on('console', on_console)",
        "",
        "        try:",
        "            started_at = datetime.now(timezone.utc).isoformat()",
        "            await step_fn(page)",
        "            ended_at = datetime.now(timezone.utc).isoformat()",
        "",
        "            duration_total = round(time.monotonic() - start_total, 4)",
        "",
        "            # -------------------------",
        "            # SUCCESS ARTIFACT CAPTURE",
        "            # -------------------------",
        "            success_step_dir = os.path.join(success_dir, step_name)",
        "            os.makedirs(success_step_dir, exist_ok=True)",
        "",
        "            await page.screenshot(path=os.path.join(success_step_dir, 'screenshot.png'))",
        "",
        "            with open(os.path.join(success_step_dir, 'console.txt'), 'w', encoding='utf-8') as f:",
        "                f.write('\\n'.join(console_logs))",
        "",
        "            step_summary = {",
        "                'step_index': step_index,",
        "                'step_name': step_name,",
        "                'intent': step_intent,",
        "                'started_at': started_at,",
        "                'ended_at': ended_at,",
        "                'duration_sec': duration_total,",
        "                'url': page.url,",
        "                'attempts': attempts,",
        "                'max_retries': max_retries,",
        "                'status': 'passed',",
        "                'flaky': attempts > 1,",
        "                'step_code_hash': hashlib.sha256(step_code.encode()).hexdigest()[:12]",
        "            }",
        "",
        "            with open(os.path.join(success_step_dir, 'step_summary.json'), 'w', encoding='utf-8') as f:",
        "                json.dump(step_summary, f, indent=2)",
        "",
        "            step_metrics.append({",
        "                'step_index': step_index,",
        "                'step_name': step_name,",
        "                'attempts': attempts,",
        "                'max_retries': max_retries,",
        "                'duration_total_sec': duration_total,",
        "                'status': 'passed',",
        "                'flaky': attempts > 1,",
        "                'step_code_hash': hashlib.sha256(step_code.encode()).hexdigest()[:12]",
        "            })",
        "",
        "            tmp = summary_path + '.tmp'",
        "            with open(tmp, 'w', encoding='utf-8') as f:",
        "                json.dump({",
        "                    'status': 'running',",
        "                    'current_step_index': step_index,",
        "                    'steps': step_metrics,",
        "                }, f, indent=2)",
        "            os.replace(tmp, summary_path)",
        "",
        "            # Live status update",
        "            with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f:",
        "                f.write('running')",
        "",
        "            return",
        "",
        "        except Exception as exc:",
        "            failures_root = os.path.join(artifacts_dir, 'failures', step_name)",
        "            attempt_dir = os.path.join(failures_root, f'attempt_{attempt + 1}')",
        "            os.makedirs(attempt_dir, exist_ok=True)",
        "",
        "            await page.screenshot(path=os.path.join(attempt_dir, 'screenshot.png'))",
        "",
        "            dom = await page.content()",
        "            dom_hash = hashlib.sha256(dom.encode()).hexdigest()",
        "",
        "            if last_dom_hash != dom_hash or attempt == max_retries:",
        "                with open(os.path.join(attempt_dir, 'dom.html'), 'w', encoding='utf-8') as f:",
        "                    f.write(dom)",
        "",
        "            last_dom_hash = dom_hash",
        "",
        "            with open(os.path.join(attempt_dir, 'console.txt'), 'w', encoding='utf-8') as f:",
        "                f.write('\\n'.join(console_logs))",
        "            with open(os.path.join(attempt_dir, 'intent.txt'), 'w', encoding='utf-8') as f:",
        "                f.write(step_intent)",
        "",
        "            with open(os.path.join(attempt_dir, 'error.txt'), 'w', encoding='utf-8') as f:",
        "                f.write(f'{type(exc).__name__}: {exc}')",
        "",
        "            with open(os.path.join(attempt_dir, 'traceback.txt'), 'w', encoding='utf-8') as f:",
        "                f.write(traceback.format_exc())",
        "",
        "            live_code = _get_step_source(step_fn)",
        "",
        "            with open(os.path.join(attempt_dir, 'step_code.py'), 'w', encoding='utf-8') as f:",
        "                f.write(live_code)",
        "",
        "            if attempt == max_retries:",
        "                duration_total = round(time.monotonic() - start_total, 4)",
        "",
        "                step_metrics.append({",
        "                    'step_index': step_index,",
        "                    'step_name': step_name,",
        "                    'attempts': attempts,",
        "                    'max_retries': max_retries,",
        "                    'duration_total_sec': duration_total,",
        "                    'status': 'failed',",
        "                    'flaky': False,",
        "                    'step_code_hash': hashlib.sha256(step_code.encode()).hexdigest()[:12]",
        "                })",
        "",
        "                tmp = summary_path + '.tmp'",
        "                with open(tmp, 'w', encoding='utf-8') as f:",
        "                    json.dump({",
        "                        'status': 'failed',",
        "                        'failed_step_index': step_index,",
        "                        'steps': step_metrics,",
        "                    }, f, indent=2)",
        "                os.replace(tmp, summary_path)",
        "",
        "                # Live failure status",
        "                with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f:",
        "                    f.write('failed')",
        "",
        "                raise",
        "",
        "            await page.wait_for_timeout(1000)",
        "",
        "        finally:",
        "            try:",
        "                if hasattr(page, 'off'):",
        "                    page.off('console', on_console)",
        "            except Exception:",
        "                pass",
    ]


def generate_playwright_test_wrapper(
    step_calls: List[str],
    test_id: str,
    run_id: str,
    target_name: str = "chromium",
    browser_engine: str = "chromium",
    device_name: str = None,
) -> List[str]:
    lines = [
        "",
        "async def test_flow():",
        "    # -------------------------",
        "    # Initialization",
        "    # -------------------------",
        "    artifacts_root = os.environ.get('ARTIFACTS_DIR')",
        "    if not artifacts_root:",
        "        artifacts_root = os.path.join(os.getcwd(), 'artifacts')",
        "",
        f"    test_case_id = '{test_id}'",
        f"    run_id = os.environ.get('RUN_ID', '{run_id}')",
        "",
        f"    test_case_dir = os.path.join(artifacts_root, test_case_id, run_id)",
        "    artifacts_dir = test_case_dir",
        "    success_dir = os.path.join(test_case_dir, 'success')",
        "    failures_dir = os.path.join(test_case_dir, 'failures')",
        "    video_tmp_dir = os.path.join(test_case_dir, '_video_tmp')",
        "",
        "    os.makedirs(success_dir, exist_ok=True)",
        "    os.makedirs(failures_dir, exist_ok=True)",
        "    os.makedirs(video_tmp_dir, exist_ok=True)",
        "",
        "    running_summary_path = os.path.join(failures_dir, 'summary.json')",
        "    step_metrics = []",
        "    error = None",
        "    summary = None",
        "",
        "    started_at = datetime.now(timezone.utc).isoformat()",
        "    finished_at = None",
        "    status = 'running'",
        "    exit_code = 1",
        "    browser = None",
        "    context = None",
        "",
        "    # -------------------------",
        "    # GUARANTEED INITIAL STATE",
        "    # -------------------------",
        "    with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f:",
        "        f.write('running')",
        "    with open(os.path.join(artifacts_dir, 'exit_code.txt'), 'w', encoding='utf-8') as f:",
        "        f.write('1')",
        "    with open(os.path.join(artifacts_dir, 'started_at.txt'), 'w', encoding='utf-8') as f:",
        "        f.write(started_at)",
        "    with open(os.path.join(artifacts_dir, 'finished_at.txt'), 'w', encoding='utf-8') as f:",
        "        f.write('')",
        "",
        "    try:",
        "        async with async_playwright() as p:",
        f"            browser = await p.{browser_engine}.launch(headless=True)"
    ]

    if device_name:
        lines.extend([
            f"            device_config = p.devices['{device_name}']",
            "            context = await browser.new_context(",
            "                **device_config,",
            "                record_video_dir=video_tmp_dir,",
            "            )",
        ])
    else:
        lines.extend([
            "            context = await browser.new_context(",
            "                record_video_dir=video_tmp_dir,",
            "                record_video_size={'width': 1280, 'height': 720},",
            "            )",
        ])
    
    lines.extend([
        "            page = await context.new_page()",
        "",
        "            # -------------------------",
        "            # Execute steps",
        "            # -------------------------",
        *[f"            {call}" for call in step_calls],
        "",
        "        # -------------------------",
        "        # Determine outcome",
        "        # -------------------------",
        "        passed = bool(step_metrics) and not any(",
        "            s.get('status') == 'failed' for s in step_metrics",
        "        )",
        "        status = 'passed' if passed else 'failed'",
        "        exit_code = 0 if passed else 1",
        "",
        "        with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f:",
        "            f.write(status)",
        "        with open(os.path.join(artifacts_dir, 'exit_code.txt'), 'w', encoding='utf-8') as f:",
        "            f.write(str(exit_code))",
        "",

        "",
        "        # -------------------------",
        "        # Final summary",
        "        # -------------------------",
        "        summary = {",
        "            'test_case_id': test_case_id,",
        "            'run_id': run_id,",
        "            'status': status,",
        "            'error': error,",
        "            'steps': step_metrics,",
        "            'failed_step_index': next(",
        "                (s.get('step_index') for s in step_metrics if s.get('status') == 'failed'),",
        "                None,",
        "            ),",
        "        }",
        "",
        "        final_summary_path = (",
        "            os.path.join(success_dir, 'summary.json')",
        "            if passed",
        "            else running_summary_path",
        "        )",
        "        tmp = final_summary_path + '.tmp'",
        "        with open(tmp, 'w', encoding='utf-8') as f:",
        "            json.dump(summary, f, indent=2)",
        "        os.replace(tmp, final_summary_path)",
        "",
        "    except Exception as exc:",
        "        error = f'{type(exc).__name__}: {exc}'",
        "        raise",
        "",
        "    finally:",
        "        finished_at = datetime.now(timezone.utc).isoformat()",
        "        try:",
        "            if context:",
        "                await context.close()",
        "            if browser:",
        "                await browser.close()",
        "        except Exception:",
        "            pass",
        "",
        "        if summary is None:",
        "            summary = {",
        "                'test_case_id': test_case_id,",
        "                'run_id': run_id,",
        "                'status': 'failed',",
        "                'error': error or 'Execution terminated before summary generation',",
        "                'steps': step_metrics,",
        "                'failed_step_index': next(",
        "                    (s.get('step_index') for s in step_metrics if s.get('status') == 'failed'),",
        "                    None,",
        "                ),",
        "            }",
        "",
        "        final_summary_path = (",
        "            os.path.join(success_dir, 'summary.json')",
        "            if summary.get('status') == 'passed'",
        "            else running_summary_path",
        "        )",
        "        try:",
        "            tmp = final_summary_path + '.tmp'",
        "            with open(tmp, 'w', encoding='utf-8') as f:",
        "                json.dump(summary, f, indent=2)",
        "            os.replace(tmp, final_summary_path)",
        "        except Exception:",
        "            pass",
        "",
        "        # -------------------------",
        "        # Video handling",
        "        # -------------------------",
        "        try:",
        "            is_passed = summary.get('status') == 'passed'",
        "            video_dst_dir = (",
        "                os.path.join(success_dir, 'video')",
        "                if is_passed",
        "                else os.path.join(failures_dir, 'video')",
        "            )",
        "            os.makedirs(video_dst_dir, exist_ok=True)",
        "            failed_step = next(",
        "                (s for s in step_metrics if s.get('status') == 'failed'),",
        "                None,",
        "            )",
        "            for root, _, files in os.walk(video_tmp_dir):",
        "                for f in files:",
        "                    if f.endswith('.webm'):",
        "                        src = os.path.join(root, f)",
        "                        if not is_passed and failed_step:",
        "                            dst = os.path.join(",
        "                                video_dst_dir,",
        "                                f\"failed_at_step_{failed_step.get('step_index')}.webm\",",
        "                            )",
        "                        else:",
        "                            dst = os.path.join(video_dst_dir, f)",
        "                        os.replace(src, dst)",
        "        except Exception:",
        "            pass",
        "",
        "        with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f:",
        "            f.write(summary['status'])",
        "        with open(os.path.join(artifacts_dir, 'exit_code.txt'), 'w', encoding='utf-8') as f:",
        "            f.write(str(exit_code))",
        "        with open(os.path.join(artifacts_dir, 'started_at.txt'), 'w', encoding='utf-8') as f:",
        "            f.write(started_at)",
        "        with open(os.path.join(artifacts_dir, 'finished_at.txt'), 'w', encoding='utf-8') as f:",
        "            f.write(finished_at)",
        "",
        "    return summary",
    ])
    return lines


def generate_playwright_runner() -> List[str]:
    return [
        "",
        "if __name__ == '__main__':",
        "    import traceback",
        "    import sys",
        "",
        "    exit_code = 1",
        "    try:",
        "        summary = asyncio.run(test_flow())",
        "        status = summary.get('status') if isinstance(summary, dict) else None",
        "        exit_code = 0 if status == 'passed' else 1",
        "    except BaseException:",
        "        traceback.print_exc()",
        "        exit_code = 1",
        "    sys.exit(exit_code)",
        "",
    ]

