from typing import List

def generate_selenium_imports() -> List[str]:
    return [
        "import os",
        "import sys",
        "import json",
        "import time",
        "import hashlib",
        "import traceback",
        "import re",
        "import threading",
        "import subprocess",
        "from datetime import datetime, timezone",
        "from selenium import webdriver",
        "from selenium.webdriver.common.by import By",
        "from selenium.webdriver.support.ui import WebDriverWait",
        "from selenium.webdriver.support import expected_conditions as EC",
        "from selenium.webdriver.support.ui import Select",
        "",
        "# Video Recording Dependencies (Requires: pip install opencv-python mss numpy)",
        "try:",
        "    import cv2",
        "    import mss",
        "    import numpy as np",
        "    HAS_VIDEO_DEPS = True",
        "except ImportError:",
        "    HAS_VIDEO_DEPS = False",
    ]

def generate_selenium_guard() -> List[str]:
    return [
        "def _get_step_source(step_fn):",
        "    try:",
        "        with open(__file__, 'r', encoding='utf-8') as f:",
        "            content = f.read()",
        "        func_name = step_fn.__name__",
        "        pattern = rf\"def\\s+{func_name}\\s*\\(\\s*driver\\s*\\)\\s*:\"",
        "        match = re.search(pattern, content)",
        "        if not match: return \"\"",
        "        start_pos = match.end()",
        "        lines = content[start_pos:].splitlines()",
        "        body_lines = []",
        "        body_indent = None",
        "        for line in lines:",
        "            if not line.strip():",
        "                if body_indent is not None: body_lines.append(line)",
        "                continue",
        "            indent = len(line) - len(line.lstrip())",
        "            if body_indent is None: body_indent = indent",
        "            if indent < body_indent: break",
        "            body_lines.append(line[body_indent:] if len(line) >= body_indent else line)",
        "        return \"\\n\".join(body_lines).strip()",
        "    except Exception:",
        "        return \"\"",
        "",
        "def _guarded_step(driver, step_fn, step_name, step_index, step_code, intent, max_retries, artifacts_dir, success_dir, step_metrics, running_summary_path):",
        "    start_total = time.monotonic()",
        "    attempts = 0",
        "    passed = False",
        "    error_message = None",
        "",
        "    while attempts <= max_retries:",
        "        attempts += 1",
        "        try:",
        "            started_at = datetime.now(timezone.utc).isoformat()",
        "            step_fn(driver)",
        "            ended_at = datetime.now(timezone.utc).isoformat()",
        "            passed = True",
        "            ",
        "            duration_total = round(time.monotonic() - start_total, 4)",
        "            success_step_dir = os.path.join(success_dir, step_name)",
        "            os.makedirs(success_step_dir, exist_ok=True)",
        "            ",
        "            try: driver.save_screenshot(os.path.join(success_step_dir, 'screenshot.png'))",
        "            except: pass",
        "            ",
        "            try:",
        "                logs = driver.get_log('browser')",
        "                with open(os.path.join(success_step_dir, 'console.txt'), 'w', encoding='utf-8') as f:",
        "                    f.write('\\n'.join(str(l) for l in logs))",
        "            except: pass",
        "            ",
        "            step_summary = {",
        "                'step_index': step_index,",
        "                'step_name': step_name,",
        "                'intent': intent,",
        "                'started_at': started_at,",
        "                'ended_at': ended_at,",
        "                'duration_sec': duration_total,",
        "                'url': driver.current_url,",
        "                'attempts': attempts,",
        "                'max_retries': max_retries,",
        "                'status': 'passed',",
        "                'flaky': attempts > 1,",
        "                'step_code_hash': hashlib.sha256(step_code.encode()).hexdigest()[:12]",
        "            }",
        "            with open(os.path.join(success_step_dir, 'step_summary.json'), 'w', encoding='utf-8') as f:",
        "                json.dump(step_summary, f, indent=2)",
        "            break",
        "        except Exception as e:",
        "            error_message = str(e)",
        "            failures_root = os.path.join(artifacts_dir, 'failures', step_name)",
        "            attempt_dir = os.path.join(failures_root, f'attempt_{attempts}')",
        "            os.makedirs(attempt_dir, exist_ok=True)",
        "            ",
        "            try: driver.save_screenshot(os.path.join(attempt_dir, 'screenshot.png'))",
        "            except: pass",
        "            ",
        "            try:",
        "                with open(os.path.join(attempt_dir, 'dom.html'), 'w', encoding='utf-8') as f:",
        "                    f.write(driver.page_source)",
        "            except: pass",
        "            ",
        "            try:",
        "                logs = driver.get_log('browser')",
        "                with open(os.path.join(attempt_dir, 'console.txt'), 'w', encoding='utf-8') as f:",
        "                    f.write('\\n'.join(str(l) for l in logs))",
        "            except: pass",
        "            ",
        "            with open(os.path.join(attempt_dir, 'intent.txt'), 'w', encoding='utf-8') as f: f.write(intent)",
        "            with open(os.path.join(attempt_dir, 'error.txt'), 'w', encoding='utf-8') as f: f.write(error_message)",
        "            with open(os.path.join(attempt_dir, 'traceback.txt'), 'w', encoding='utf-8') as f: f.write(traceback.format_exc())",
        "            with open(os.path.join(attempt_dir, 'step_code.py'), 'w', encoding='utf-8') as f: f.write(_get_step_source(step_fn))",
        "            ",
        "            if attempts <= max_retries:",
        "                print(f'Step {step_index} failed, retrying ({attempts}/{max_retries})...')",
        "                time.sleep(1)",
        "",
        "    duration = time.monotonic() - start_total",
        "    metric = {",
        "        'step_index': step_index,",
        "        'step_name': step_name,",
        "        'attempts': attempts,",
        "        'max_retries': max_retries,",
        "        'duration_total_sec': round(duration, 3),",
        "        'status': 'passed' if passed else 'failed',",
        "        'flaky': attempts > 1 and passed,",
        "        'step_code_hash': hashlib.sha256(step_code.encode()).hexdigest()[:12]",
        "    }",
        "    if not passed:",
        "        metric['error'] = error_message",
        "",
        "    step_metrics.append(metric)",
        "    ",
        "    with open(running_summary_path, 'w', encoding='utf-8') as f:",
        "        json.dump({'status': 'running', 'steps': step_metrics}, f, indent=2)",
        "",
        "    if not passed:",
        "        raise RuntimeError(f'Step {step_index} failed after {max_retries} retries: {error_message}')",
        "",
        "def _record_screen(stop_event, filepath):",
        "    if not HAS_VIDEO_DEPS: return",
        "    fourcc = cv2.VideoWriter_fourcc(*'mp4v')",
        "    out = None",
        "    try:",
        "        with mss.MSS() as sct:",
        "            monitor = sct.monitors[1]",
        "            out = cv2.VideoWriter(filepath, fourcc, 10.0, (monitor['width'], monitor['height']))",
        "            while not stop_event.is_set():",
        "                img = np.array(sct.grab(monitor))",
        "                frame = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)",
        "                out.write(frame)",
        "                time.sleep(0.1)",
        "    except Exception:",
        "        pass",
        "    finally:",
        "        if out: out.release()",
    ]

def generate_selenium_test_wrapper(step_calls: List[str], test_id: str, run_id: str) -> List[str]:
    lines = [
        "def test_flow():",
        "    artifacts_root = os.environ.get('ARTIFACTS_DIR', os.path.join(os.getcwd(), 'artifacts'))",
        f"    test_case_dir = os.path.join(artifacts_root, '{test_id}', os.environ.get('RUN_ID', '{run_id}'))",
        "    artifacts_dir = test_case_dir",
        "    success_dir = os.path.join(test_case_dir, 'success')",
        "    failures_dir = os.path.join(test_case_dir, 'failures')",
        "    video_tmp_dir = os.path.join(test_case_dir, '_video_tmp')",
        "    os.makedirs(success_dir, exist_ok=True)",
        "    os.makedirs(failures_dir, exist_ok=True)",
        "    os.makedirs(video_tmp_dir, exist_ok=True)",
        "    running_summary_path = os.path.join(failures_dir, 'summary.json')",
        "",
        "    # Initialize status files",
        "    with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f: f.write('running')",
        "    with open(os.path.join(artifacts_dir, 'exit_code.txt'), 'w', encoding='utf-8') as f: f.write('1')",
        "    with open(os.path.join(artifacts_dir, 'started_at.txt'), 'w', encoding='utf-8') as f: f.write(datetime.now(timezone.utc).isoformat())",
        "",
        "    step_metrics = []",
        "    driver = None",
        "    stop_video_event = threading.Event()",
        "    video_thread = None",
        "    video_tmp_path = os.path.join(video_tmp_dir, 'recording.mp4')",
        "    ",
        "    if HAS_VIDEO_DEPS:",
        "        video_thread = threading.Thread(target=_record_screen, args=(stop_video_event, video_tmp_path))",
        "        video_thread.start()",
        "",
        "    try:",
        "        options = webdriver.ChromeOptions()",
        "        options.add_argument('--headless=new')",
        "        options.add_argument('--no-sandbox')",
        "        options.add_argument('--disable-dev-shm-usage')",
        "        options.set_capability('goog:loggingPrefs', {'browser': 'ALL'})",
        "        driver = webdriver.Chrome(options=options)",
        "        driver.set_window_size(1280, 720)",
        "        driver.implicitly_wait(10)",
        "",
        "        # Steps",
    ]
    
    for call in step_calls:
        lines.append(f"        {call}")

    lines.extend([
        "",
        "        # Determine Outcome",
        "        passed = not any(s.get('status') == 'failed' for s in step_metrics)",
        "        status = 'passed' if passed else 'failed'",
        "        with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f: f.write(status)",
        "        with open(os.path.join(artifacts_dir, 'exit_code.txt'), 'w', encoding='utf-8') as f: f.write('0' if passed else '1')",
        "",
        "    except Exception as e:",
        "        with open(os.path.join(artifacts_dir, 'status.txt'), 'w', encoding='utf-8') as f: f.write('failed')",
        "        with open(os.path.join(artifacts_dir, 'exit_code.txt'), 'w', encoding='utf-8') as f: f.write('1')",
        "        raise e",
        "    finally:",
        "        with open(os.path.join(artifacts_dir, 'finished_at.txt'), 'w', encoding='utf-8') as f: f.write(datetime.now(timezone.utc).isoformat())",
        "        if driver:",
        "            driver.quit()",
        "        ",
        "        stop_video_event.set()",
        "        if video_thread:",
        "            video_thread.join(timeout=5)",
        "        ",
        "        passed = not any(s.get('status') == 'failed' for s in step_metrics)",
        "        if os.path.exists(video_tmp_path):",
        "            video_dst_dir = os.path.join(success_dir, 'video') if passed else os.path.join(failures_dir, 'video')",
        "            os.makedirs(video_dst_dir, exist_ok=True)",
        "            os.replace(video_tmp_path, os.path.join(video_dst_dir, 'recording.mp4'))",
        "",
        "        # Write summary.json",
        f"        summary = {{",
        f"            'test_case_id': '{test_id}',",
        f"            'run_id': os.environ.get('RUN_ID', '{run_id}'),",
        f"            'status': 'passed' if passed else 'failed',",
        f"            'steps': step_metrics,",
        f"            'failed_step_index': next((s.get('step_index') for s in step_metrics if s.get('status') == 'failed'), None),",
        f"        }}",
        "        summary_path = os.path.join(success_dir if passed else failures_dir, 'summary.json')",
        "        try:",
        "            tmp = summary_path + '.tmp'",
        "            with open(tmp, 'w', encoding='utf-8') as f:",
        "                json.dump(summary, f, indent=2)",
        "            os.replace(tmp, summary_path)",
        "        except Exception:",
        "            pass",
        "    ",
    ])
    return lines

def generate_selenium_runner() -> List[str]:
    return [
        "if __name__ == '__main__':",
        "    try:",
        "        test_flow()",
        "        sys.exit(0)",
        "    except Exception:",
        "        traceback.print_exc()",
        "        sys.exit(1)",
    ]
